packages:
  - 'clients/*'
  - 'webapp'
  - 'webapp/api'
  - 'webapp/scripts'

overrides:
  bn.js: 5.2.3
  flatted: 3.4.2
  minimatch: 9.0.9
  picomatch: 4.0.4
  rollup: 4.60.2
  "ws@^8.0.0": 8.20.1
  toml: ^5.0.0
  serialize-javascript: ^7.1.1
  uuid: ^11.1.1
  diff: ^8.0.3
